export const TICKER_ITEMS = [
  ['Chloe Kim', '4th place, World Junior Championships 2025'],
  ['Timothy Lee', 'Commits to Harvard University'],
  ['Kate Hurst', 'USA National Team 2024–2025'],
  ['Jacob Kim', 'Commits to Carnegie Mellon'],
  ['Jessica Wolf', 'Commits to Colgate University'],
  ['Rebekah Jung', 'Commits to University of Rochester'],
  ['Jonas Emerson', 'Commits to Wesleyan University'],
  ['Ryker Levi', 'Junior National Qualifier 2025'],
  ['Harrison Lee', 'Commits to Lehigh University'],
  ['Sienna Plutzer', 'Commits to Holy Cross University'],
]

export const STATS = [
  { num: '5+', label: 'Years coaching elite swimmers' },
  { num: '20+', label: 'College placements, D1 to D3' },
  { num: '12th', label: 'All-time US 1500m Freestyle record' },
  { num: '4th', label: 'World Junior Aquatics Championships 2025' },
]

const CDN2 = 'https://images.squarespace-cdn.com/content/v1/613a5c22540e534e72bda9a1/'
export const ARTICLES = {
  'ethan-state-record': {
    tag: 'Competition',
    date: 'March 27, 2026',
    title: 'Ethan Reines Breaks the 13-14 State Record in the 500 Freestyle',
    img: 'https://images.squarespace-cdn.com/content/v1/613a5c22540e534e72bda9a1/5c030ab9-385e-42d4-9fe0-dfd038431410/79624924812__79255E09-69B2-4832-8BEE-1511FA5B9790.jpeg',
    imgPos: 'center 40%',
    excerpt: 'Ethan Reines, age 14, breaks the New Jersey State Record in the 500 Freestyle with a time of 4:30.88 at the 2026 NJS & Scarlet 11 & Over Gold Championships.',
    body: [
      '2026 NJS & Scarlet 11 & Over Gold Championships — March 19-22 at Sonny Werblin Recreation Center',
      'Ethan Reines, age 14, achieved a major milestone by breaking the New Jersey State Record in the 500 Freestyle with a time of 4:30.88 on March 20th.',
      'Meet Highlights:',
      'March 19: Reines secured first place in the 1650 Freestyle (15:48.39). Teammate Sebastian Hendrawan posted 16:07.22 in the same event.',
      'March 20: Beyond the record swim, Joshua Reines and Yuriel Lee both achieved lifetime bests in the 200 Individual Medley (1:51.64 and 1:51.49 respectively). Chase Kim recorded 50.91 in the 100 Butterfly.',
      'March 21-22: The team continued excelling, with Joshua Reines breaking the 4-minute barrier in the 400 Individual Medley (3:59.61), and Ethan Reines finishing at 3:58.98.',
      'Congratulations to all the swimmers for their hard work and dedication throughout the weekend, with several advancing to Sectionals and YMCA Nationals!',
    ],
  },
  'tyr-2026': {
    tag: 'Competition',
    date: 'January 19, 2026',
    title: '2026 TYR LC Winter Invitational',
    img: CDN2 + '1768921889010-CI1NQOOZMBGTLGYH81VB/IMG_2412.JPEG',
    imgPos: 'center 40%',
    excerpt: 'Ryker Levi qualifies for Toyota Nationals in the 100M & 200M Butterfly. Joshua Reines earns his first Winter Junior National qualification in the 400 IM.',
    body: [
      'January 16th - January 18th - Sonny Werblin Recreation Center',
      'Toyota National & Winter Junior National Qualifiers',
      'A series of disciplined and high-level performances highlighted a strong showing from our athletes, resulting in national qualifying standards and numerous lifetime bests.',
      'Our Qualifiers:',
      'Ryker Levi led the group by qualifying for the Toyota National Championships in both the 100M Butterfly (54.45) and 200M Butterfly (2:02.87). The meet stands among USA Swimming\'s premier events and serves as a key selection opportunity for U.S. National Teams.',
      'Joshua Reines added to the success with his first Winter Junior National qualification in the 400 IM (4:33.93).',
      'Ava Lan earned her Winter Junior National qualifying standard last month in the 1000Y Freestyle, recording a lifetime best of 10:09.18.',
      'Honorable Mentions:',
      'Joshua Reines (16) drops over 2 seconds in the 100M Breast w/ a lifetime best of 1:06.73!',
      'Ethan Reines (14) goes a lifetime best in the 200M Free in a time of 1:58.18. A best time in the 400M Free with a time of 4:08.91. He also goes a lifetime best in the 1500M Free in a time of 16:27.01 placing 10th!',
      'Chase Kim (14) goes best times in the 100M and 200M fly with a time of 58.43 & 2:07.83 respectively!',
    ],
  },
  'chloe-worlds': {
    tag: 'World Championships',
    date: 'August 23, 2025',
    title: 'Chloe Kim Places 4th at the World Junior Aquatics Championships!',
    img: CDN2 + '1757435504199-7JNV92ONPYDVPLF8MQ30/World+Juniors.png',
    imgPos: 'center 70%',
    excerpt: 'Our very own Chloe Kim delivered an incredible performance on the world stage, finishing 4th in the world with a lifetime best of 16:22.56!',
    body: [
      'Our very own Chloe Kim delivered an incredible performance on the world stage, finishing 4th in the world with a lifetime best of 16:22.56!',
      'This is an extraordinary accomplishment, and we couldn\'t be prouder of Chloe and her family for their dedication and commitment to excellence.',
      'Wishing Chloe the best of luck as she takes the next step in her journey at Princeton University — Go Tigers! 🐅',
    ],
  },
  'jonas-wesleyan': {
    tag: 'College Commitment',
    date: 'November 11, 2025',
    title: 'Jonas Emerson Commits to Wesleyan University',
    img: CDN2 + '1763302742372-VYK1VZZKBPAA4NAQTF5X/Wesleyan.jpg',
    imgPos: 'center 25%',
    excerpt: '"I am very excited to announce my commitment to Wesleyan University to further my academic and athletic career!"',
    body: [
      'I am very excited to announce my commitment to Wesleyan University to further my academic and athletic career! I\'d like to thank my Condors coaches, Phil, and all of my family and friends for supporting me along the way. I\'d also like to give a special thanks to Coach Williamson for giving me this amazing opportunity. Go Cardinals! 🔴⚫️',
      'Congratulations Jonas!!',
    ],
  },
  'rebekah-rochester': {
    tag: 'College Commitment',
    date: 'November 7, 2025',
    title: 'Rebekah Jung Commits to the University of Rochester',
    img: CDN2 + '1763303017571-59SHN1ZWRQIT4OREL4FV/Rebekah+Jung.jpg',
    imgPos: 'center 20%',
    excerpt: '"I am excited to announce my verbal commitment to continue my academic and athletic career at the University of Rochester!"',
    body: [
      'I am excited to announce my verbal commitment to continue my academic and athletic career at the University of Rochester!',
      'I would like to thank my parents, coaches, and friends for the continued support.',
      'Big thanks to the coaches and staff at URochester for this incredible opportunity!',
      'So grateful and excited for this next chapter!',
      'Go jackets! 🐝💙💛',
      'Congratulations Rebekah!!',
    ],
  },
  'jacob-cmu': {
    tag: 'College Commitment',
    date: 'November 2, 2025',
    title: 'Jacob Kim Commits to Carnegie Mellon University',
    img: CDN2 + '1762190250415-C90XUZ0KXTC5KVENSJJR/Jacob+Commits+to+Carnegie+Mellon.jpg',
    imgPos: 'center 20%',
    excerpt: '"I am honored to announce my verbal commitment to the academic process at Carnegie Mellon University!"',
    body: [
      'I am honored to announce my verbal commitment to the academic process at Carnegie Mellon University!',
      'I would like to thank my coaches, family, and everyone else who has helped me become the person I am today.',
      'I would also like to thank Coach Kinney for this amazing opportunity.',
      'GO TARTANS!',
      'Congratulations on the commitment Jacob!',
    ],
  },
  'jessica-colgate': {
    tag: 'College Commitment',
    date: 'October 26, 2025',
    title: 'Jessica Wolf Commits to Colgate University',
    img: CDN2 + '1762189818941-1RC3X9NYU3MKFS7ZVMO6/Jessie+Wolf+commits+to+Colgate+University.jpg',
    imgPos: 'center 20%',
    excerpt: '"I am so excited to announce my commitment to continue my academic and athletic career at Colgate University!"',
    body: [
      'I am so excited to announce my commitment to continue my academic and athletic career at Colgate University!',
      'I\'d like to thank my family, friends, coaches, and teammates for supporting me throughout this journey.',
      'I am so grateful to Coach Ed for this amazing opportunity and I can\'t wait for the next four!',
      'GO \'GATE!',
      'Congratulations on the commitment Jessica and family!',
    ],
  },
  'sienna-holycross': {
    tag: 'College Commitment',
    date: 'September 24, 2025',
    title: 'Sienna Plutzer Commits to Holy Cross University',
    img: CDN2 + '1762189559773-A432QAWJ3081AJNK604W/Sienna+Sacred+Heart.jpg',
    imgPos: 'center 20%',
    excerpt: '"I am beyond excited to announce my verbal commitment to swim D1 and continue my academic careers at Holy Cross!"',
    body: [
      'I am beyond excited to announce my verbal commitment to swim D1 and continue my academic careers at Holy Cross!',
      'First, I would like to thank my family for their endless support throughout this process.',
      'I would also like to thank my teammates, coaches, and friends for pushing me every day.',
      'Lastly, a huge thanks to Coach Kristy and Coach Kate for giving me this opportunity.',
      'I can\'t wait to be apart of this amazing program!',
      'Go Crusaders💜',
      'Congratulations on the commitment Sienna and family!',
    ],
  },
  'harrison-lehigh': {
    tag: 'College Commitment',
    date: 'August 8, 2025',
    title: 'Harrison Lee Commits to Lehigh University',
    img: CDN2 + '1762189435887-LS6BS9O946JF5B24GILK/Harrison+Lee+commits.jpg',
    imgPos: 'center 20%',
    excerpt: '"I am thrilled to announce my commitment to Lehigh University to continue my academic and athletic career."',
    body: [
      'I am thrilled to announce my commitment to Lehigh University to continue my academic and athletic career.',
      'Thank you to Coach Rob and Coach Wydan for this opportunity.',
      'I also would like to thank my friends, family, and coaches for helping me along the way.',
      'Go mountain hawks 🦅!',
      'Congratulations on the commitment Harrison and family!',
    ],
  },
  'junior-nationals-qualifiers': {
    tag: 'Competition',
    date: 'July 31, 2025',
    title: 'New Junior National Qualifiers',
    img: CDN2 + '1757436055642-34YX1R1QZ4E2NLGG4WEL/Yuriel+Junior+National.jpg',
    imgPos: 'center 30%',
    excerpt: 'July was an incredible month of racing, with our athletes reaching major milestones on the national stage!',
    body: [
      'July was an incredible month of racing, with our athletes reaching major milestones on the national stage!',
      'July 12 – Los Angeles Invite (Day 2): Yuriel Lee achieved his first Winter Junior National cut in the 200M Backstroke, posting a lifetime best of 2:08.21.',
      'July 25 – 2024 NJ LC Gold Championships (Day 1): Jacob Kim earned his first Summer Junior National qualification in the 100M Backstroke with an impressive time of 57.81.',
      'July 29 – 2025 YMCA Nationals (Day 1): Ryker Levi powered through the 200M Butterfly to secure his first Winter Junior National cut, finishing with a best time of 2:05.96.',
      'July 31 – 2025 YMCA Nationals (Day 3): Ryker continued his momentum, dropping more than 1.5 seconds in the 100M Butterfly to achieve his first Summer Junior National cut.',
      'His time of 55.89 earned him an impressive 5th-place finish.',
      'Congratulations to Yuriel, Jacob, and Ryker for their dedication, hard work, and remarkable achievements.',
      'We are proud of their commitment to excellence and excited to see what\'s ahead!',
    ],
  },
  'chloe-qualifies-worlds': {
    tag: 'Competition',
    date: 'June 8, 2025',
    title: 'Chloe Kim Qualifies For The World Aquatics Junior Swimming Championships 2025',
    img: CDN2 + '1749494202074-QQKXRI3U855YC2JAE112/754ff89c-5265-46ac-bf63-fdb5d3f19e1f.png',
    imgPos: 'center 40%',
    excerpt: 'We\'re proud to announce that Chloe Kim has earned a spot on the World Aquatics Junior Team and will represent Team USA in the 1500M Freestyle.',
    body: [
      'We\'re proud to announce that Chloe Kim of Scarlet Aquatics has earned a spot on the World Aquatics Junior Team and will represent Team USA in the 1500M Freestyle at the World Aquatics Junior Swimming Championships—the premier global competition for swimmers under 18.',
      'Chloe secured her place on the team after an impressive performance at the 2025 National Championships, where she placed 11th overall in the 1500M Freestyle with a time of 16:30.92, narrowly missing her personal best of 16:28.77.',
      'She also set a new personal best in the 800M Freestyle, finishing 15th with a time of 8:42.31.',
      'Congratulations to Chloe, her family, and all the coaches who have supported her throughout this incredible journey.',
      'We\'re excited to cheer her on as she takes the world stage!',
    ],
  },
  'ymca-nationals-2025': {
    tag: 'Competition',
    date: 'April 7, 2025',
    title: '2025 YMCA Short Course Nationals',
    img: CDN2 + '1749494896586-TXCJSMLGZ12XSI3XPOXE/b4ecf5db-cf13-4afb-92bc-a48901bccebe.jpg',
    imgPos: 'center 40%',
    excerpt: 'Our athletes showcased grit, speed, and determination throughout the competition, earning impressive lifetime bests and top finishes!',
    body: [
      'March 31 - April 4 2025 - Greensboro Aquatic Complex',
      'Our athletes showcased grit, speed, and determination throughout the competition, earning impressive lifetime bests and top finishes!',
      'March 31: Sebastian Hendrawan dropped more than 6 seconds in the 1000y Freestyle, finishing 25th with a lifetime best of 9:43.94.',
      'April 1: Harrison Lee shaved a full second off his time in the 100y Butterfly, placing 11th at 48.96.',
      'Jessie Wolf delivered a strong swim in the 200y Backstroke, dropping over a second to finish with a best time of 2:06.41.',
      'In the 200y Breaststroke, both Sebastian Hendrawan (2:08.27) and Alex Hwang (2:09.15) achieved lifetime bests.',
      'April 2: Ryker Levi cut more than a second from his 100y Backstroke, touching at 50.84 for 25th place.',
      'Sebastian Hendrawan continued his momentum in the 400 IM, posting a lifetime best of 4:07.61 for 27th place.',
      'April 4: Jessie Wolf secured a 5th-place finish in the 100y Freestyle with a lifetime best of 50.64.',
      'Ryker Levi also set a lifetime best in the 100y Freestyle with 45.89, placing 25th.',
      'Alex Hwang broke the one-minute barrier in the 100y Breaststroke, posting a personal best of 59.91.',
      'Harrison Lee closed strong with a 13th-place finish in the 200y Butterfly, clocking 1:51.33.',
      'Congratulations to all our swimmers for their hard work, time drops, and competitive spirit.',
    ],
  },
  'east-coast-elite-2025': {
    tag: 'Competition',
    date: 'April 6, 2025',
    title: '2025 East Coast Elite Showcase',
    img: CDN2 + '1745340288812-1HXNL8X77EZX0109KI71/25-isca-East-Elite-Showcase-logo-min.png',
    imgPos: 'center 40%',
    excerpt: 'Our 12–13-year-old athletes had an incredible week at the Youth Championships, achieving impressive time drops, personal bests, and podium finishes!',
    body: [
      'April 2 - April 5, 2025 - North Shore Aquatic Complex',
      'Our 12–13-year-old athletes had an incredible week at the Youth Championships, achieving impressive time drops, personal bests, and podium finishes!',
      'April 2: Atticus Gutierrez-Ewing (12) won the 200y Breaststroke (2:22.78). Xavier Lee (12) placed 3rd in the 50y Back (27.44). Chase Kim (13) won the 50y Back (25.25), and Ethan Reines (13) placed 3rd in the 50y Back (25.58) and 2nd in the 200y Breast (2:11.45).',
      'April 3: Atticus placed 4th in the 200IM (2:09.62) and won the 50y Breast (30.23). Chase Kim won the 200y Butterfly (1:54.34), Ethan Reines was 2nd (1:58.83), and Aahana Tibb (13) placed 5th (2:09.94).',
      'April 4: Atticus posted a PB in the 100 IM (1:01.47) and won the 100y Breast (1:06.79). Xavier Lee set a PB in the 100 IM (1:01.63) and placed 8th in the 100y Fly (1:00.11). Chase Kim placed 2nd in the 100y Fly (52.92).',
      'April 5: Chase Kim won the 50y Fly (23.85) and placed 2nd in the 200y Free (1:47.34). Ethan Reines took 2nd in the 100y Back (55.17).',
      'Congratulations to Atticus, Chase, Ethan, Xavier, and Aahana for an outstanding week of performances and personal bests!',
    ],
  },
  'speedo-sectionals-2025': {
    tag: 'Competition',
    date: 'April 1, 2025',
    title: '2025 Central & North Speedo Sectional Championships',
    img: CDN2 + '1743906290447-0OIX1WBTV7TSVY5TX742/Sectionals.png',
    imgPos: 'center 40%',
    excerpt: 'Chloe Kim wins three events including the 800M Freestyle and 1500M Freestyle at the Speedo Sectional Championships.',
    body: [
      'March 27-30, 2025 - Indiana University Natatorium / Ecc Burt Flickinger Center / Ithaca College',
      '3/27/2025: Chloe Kim wins the 800M Freestyle with a personal best time of 8:44.24.',
      'Caden Cho swims a personal best in the 1500M Freestyle in a time of 16:45.25.',
      'Kevin Son goes best time in the 800M Freestyle in a time of 8:52.05.',
      'Dimitri Melnikov places 3rd in a lifetime best in the 100y breaststroke with a time of 54.75.',
      'William Mulder swims a best time in the 100y breast in a time of 58.58.',
      '3/28/2025: Chloe Kim places 3rd in the 400M IM in a time of 4:47.72.',
      'Cheryn Cho goes a lifetime best in the 100M Butterfly in a time of 1:05.62.',
      'Dimitri Melnikov goes a lifetime best in the 200y Breaststroke in a time of 2:00.26 placing second.',
      '3/29/2025: Chloe Kim wins the 400M Freestyle in a personal best of 4:15.02.',
      'Jacob Kim places 10th in the 100M backstroke in a time of 58.23.',
      'Cheryn Cho drops 5 seconds in the 200M Butterfly for a personal best time of 2:26.91.',
      '3/30/2025: Chloe Kim wins the 1500M Freestyle in a time of 16:41.16!',
      'Timothy Lee places 10th in the 100M Freestyle in a time of 52.55.',
    ],
  },
  'njs-scarlet-gold-2025': {
    tag: 'Competition',
    date: 'March 24, 2025',
    title: '2025 NJS & Scarlet Gold Championships',
    img: CDN2 + '1745340373510-CC3GMXQI06876E8UYTRB/scarletlogo_082039.jpg',
    imgPos: 'center 40%',
    excerpt: 'Ethan Reines earns his first Futures cut. Chloe Kim wins the 200y Butterfly in a lifetime best of 1:56.19.',
    body: [
      'March 20-23, 2025 - Sonny Werblin RECreation Center',
      '3/20/2025: 13Y/O Ethan Reines makes his first Futures cut in the 1650y Freestyle with a time of 15:58.32.',
      '3/21/2025: 13Y/O Chase Kim and Ethan Reines go 1 & 2 in 200y IM with a time of 1:58.62 & 1:59.55 respectively.',
      'Ethan also places first in the 500y Freestyle in a time of 4:41.77.',
      'Madelyn Raguindin wins the 200y IM in a best time of 2:07.74.',
      'Madelyn and Sienna Plutzer go 2 & 3 in the 200y breaststroke in a time of 2:20.64 & 2:23.96 respectively.',
      'Jacob Kim goes a personal best time in the 200y IM with a time of 1:50.77.',
      '3/22/2025: Yuriel Lee breaks 1:50 for the first time in the 200y Backstroke in a time of 1:49.58!',
      'Chloe Kim wins the 200y Butterfly in a lifetime best of 1:56.19!',
      '3/23/2025: Jacob Kim breaks 50s in the 100y Backstroke with a lifetime best of 49.57!',
    ],
  },
  'holiday-classic-2025': {
    tag: 'Competition',
    date: 'January 13, 2025',
    title: 'EEX Holiday Classic XXXVII & 2025 TYR LC Winter Invitational',
    img: CDN2 + '1736797148196-0WS9ULYM7QP4SC4KJOLQ/Stephanie+Kim+Junior+Nats.jpg',
    imgPos: 'center 20%',
    excerpt: 'Stephanie Kim makes her first Winter Junior National Cut. Chloe Kim makes her Junior National cut in the 100 Fly.',
    body: [
      'December 20-22, 2024 / January 12-14, 2025 - Sonny Werblin RECreation Center',
      '12/20/2024: Stephanie Kim makes her first Winter Junior National Cut in the 200y Breaststroke clocking in a personal best time of 2:16.59.',
      'Ethan Reines makes his first sectional cut in the 200y butterfly in a time of 2:00.54.',
      '12/21/2024: Chloe Kim makes her Junior National cut in the 100Fly in a time of 53.48.',
      'Joshua Reines makes his first futures cut in the 200y Breaststroke in a time of 2:07.49.',
      '01/12/2025: Stephanie Kim makes her first Summer Junior National cut and US Open cut in the 100M breaststroke in a time of 1:13.24. Joshua Reines makes his second Futures cut in the 200M IM in a time of 2:12.79.',
      'Congratulations to our swimmers!',
    ],
  },
  'winter-juniors-2024': {
    tag: 'Competition',
    date: 'December 15, 2024',
    title: '2024 Winter Junior Championships – East',
    img: CDN2 + '1734452985162-JRE34SC876PS40S4T7BO/Winter+Juniors+Logo.jpg',
    imgPos: 'center 40%',
    excerpt: 'Chloe Kim wins the 500y Freestyle, 400y IM (breaking the NJ state record!), and 1650y Freestyle at Junior Nationals.',
    body: [
      'Junior Nationals - East, took place at the Greensboro Aquatic Center in Greensboro, North Carolina on Wednesday morning where all the top 18&U qualifiers gathered to compete.',
      'On day two, Chloe Kim posts a life time personal best of 4:43.31 in the 500y Freestyle. Dropping over 2 seconds to be seeded first going into finals.',
      'Chloe also swims a lifetime best in the 200y IM in a time of 1:59.30 placing her 9th going into finals.',
      'Jacob Kim places 108th in the 200y IM with a time of 1:52.79, just shy off his best time.',
      'At finals, Chloe Kim wins the 500y Freestyle in a time of 4:42.33, dropping another second from her morning swim!',
      'Chloe Kim wins the 400y IM in a time of 4:07.11 dropping 3 seconds, also breaking the New Jersey state record!',
      'Chloe also places 14th in the 200y Freestyle at finals.',
      'Jacob Kim places 87th in the 200y Freestyle in a time of 1:41.58 and shortly after 107th in the 100y Backstroke in a time of 52.14.',
      'Kayla Rodriguez places 50th in the 100y Breaststroke in a time of 1:03.73.',
      'Chloe Kim wins the 1650y Freestyle in a lifetime personal best of 16:00.21 dropping over 16 seconds!',
      'She also swims a lifetime personal best in the 200y Butterfly in prelims with a time of 1:56.94.',
      'Kayla Rodriguez swims the 200y Breaststroke in a time of 2:16.96 which is just off her best time, placing her 31st!',
      'Kayla swims the 200y Butterfly shortly after placing 73rd.',
    ],
  },
  'roy-lafayette': {
    tag: 'College Commitment',
    date: 'October 29, 2024',
    title: 'Roy Dafinoiu Commits to Lafayette College',
    img: CDN2 + '1730218140435-VXX4ILSW54SKK2N09EEM/Roy+LAF.jpg',
    imgPos: 'center 20%',
    excerpt: '"I am excited to announce my verbal commitment to continue my academic and athletic career at Lafayette College!"',
    body: [
      'I am excited to announce my verbal commitment to continue my academic and athletic career at Lafayette College!',
      'I would like to thank my family, coaches, and teammates for all their support.',
      'I would also like to thank Coach Dailey and Coach Rinde for this amazing opportunity.',
      'Roll Pards!!',
      'Congratulations on the commitment Roy and family!',
    ],
  },
  'timothy-harvard': {
    tag: 'College Commitment',
    date: 'October 28, 2024',
    title: 'Timothy Lee Commits to Harvard University',
    img: CDN2 + '1730135596929-CT3TH0EQRII0VQI725SB/Timothy+Harvard.jpg',
    imgPos: 'center 20%',
    excerpt: '"I am very grateful to announce my verbal commitment to the admissions process to further my athletic and academic career at Harvard University."',
    body: [
      'I am very grateful to announce my verbal commitment to the admissions process to further my athletic and academic career at Harvard University.',
      'I would like to thank my father, mother, brother, coaches, teammates, and friends for pushing me always.',
      'I would also like to thank Coach Kevin and Coach Daniel for giving me this opportunity.',
      'Go Crimson!',
      'Timothy Lee will be joining his brother Eric Lee at Harvard University.',
      'Congratulations on the commitment Timothy and Family!',
    ],
  },
  'kate-national': {
    tag: 'National Team',
    date: 'October 9, 2024',
    title: 'Kate Hurst Makes the 2024–2025 USA National Team',
    img: CDN2 + '1731428215434-9FS9VU8Z5XPAH034V7OE/Kate+Hurst+Budapest.jpg',
    imgPos: 'center 20%',
    excerpt: 'Kate Hurst will be competing at the 2024 World Aquatics Championships (25M) in Budapest, Hungary from December 10-15.',
    body: [
      'Kate Hurst will be competing at the 2024 World Aquatics Championships (25M) in Budapest, Hungary from December 10-15.',
      'Congratulations on being a part of the USA National team and good luck in Hungary!',
    ],
  },
  'speedo-summer-2024': {
    tag: 'Competition',
    date: 'August 1, 2024',
    title: '2024 Speedo Summer Championships',
    img: CDN2 + '1722206572624-77MDCCP2W34EG2J14H4X/Speedo.png',
    imgPos: 'center 40%',
    excerpt: 'Kate Hurst wins High Point at the 2024 Speedo Summer Championships!',
    body: [
      '07/23/24 - 07/27/24 - William Woollett Jr. Aquatic Center Irvine, CA',
      '7/23: The combined Junior and Senior Nationals took place at the William Woollett Jr. Aquatic Center in Irvine California on Tuesday morning.',
      'On day one, Kayla Rodriguez posts a best time in the 100M Breaststroke in a time of 1:12.87 and places 43rd.',
      'Timothy Lee also posts his best time in the 100M Butterfly in a time of 57.15.',
      'Raymond Stelmark swims the 1500M Freestyle and goes a personal best in a time of 16:11.10.',
      'Chloe Kim finishes 9th in the 800M Freestyle in a time of 8:49.32.',
      'At finals, Richard Poplawski goes a personal best in the 200M Butterfly in a time of 2:01.40, placing 18th.',
      'Kate Hurst finishes 3rd in the 800M Freestyle in a time of 8:34.17.',
      '7/24: At finals, Timothy Lee swims the 100M Freestyle in a best time of 51.75 placing 31st at finals.',
      'Chloe Kim finishes 3rd in the 400M Individual Medley in a time of 4:47.50 and Kate Hurst finishes 6th in a time of 4:49.43.',
      'Richard Poplawski places 13th in the 400M individual Medley in a time of 4:26.82 and Eric Lee finishes 23rd in a time of 4:30.59.',
      '7/25: Kate Hurst places 3rd in the 400M Freestyle in a lifetime best of 4:10.89!',
      'Chloe Kim places 17th in the 400M Freestyle in a time of 4:17.49.',
      'Richard Poplawski finishes 22nd in the 100M Butterfly in a time of 54.96.',
      'Chloe Kim finishes 26th in the 200M Backstroke in a time of 2:18.18.',
      'Lastly, Eric Lee places 5th in the 200M Backstroke in a time of 2:02.59.',
      '7/26: Kate Hurst places 4th in the 200M Freestyle in a lifetime best of 2:00.32!',
      'Chloe Kim finishes 32nd in a time of 2:05.84.',
      'Eric Lee places 19th in the 100M backstroke in a time of 57.61.',
      'Kayla Rodriguez swims a personal best in the 200M Breaststroke in a time of 2:36.54 and finishes 28th.',
      '7/27: Kate Hurst places 2nd in the 1500M Freestyle in a time of 16:13.97.',
      'Chloe Kim finishes 7th in the in a time of 16:50.90.',
      'Raymond Stelmark goes a lifetime best in the 800M Freestyle in a time of 8:28.88 finishing 34th.',
      'Richard Poplawski finishes 12th in the 200M Individual Medley in a time of 2:03.87 and Eric Lee finishes 25th in a time of 2:06.64.',
      'Kate Hurst wins High Point at the 2024 Speedo Summer Championships!',
    ],
  },
  'olympic-trials': {
    tag: 'Competition',
    date: 'June 21, 2024',
    title: '2024 U.S. Olympic Team Trials',
    img: '/peakaquatics1/photos/kate-olympic-trials.jpg',
    imgPos: 'center top',
    excerpt: 'Kate Hurst places 4th at finals in the 1500M Freestyle and 6th in the 800M Freestyle at the U.S. Olympic Team Trials!',
    body: [
      'June 15 - 23, 2024 - Lucas Oil Stadium, IN',
      'Kate Hurst places 4th at finals in the 1500M Freestyle in a time of 16:09.77 and 6th at finals in the 800M Freestyle in a lifetime best of 8:28.92! She also placed 19th in the 400M in a time of 4:12.13 which is just shy of her lifetime best of 4:11.71.',
      'Chloe Kim places 32nd in the 1500M in a time of 17:00.66.',
      'Richard Poplawski places 43rd in the 400M Individual Medley in a time of 4:25.83 and places 57th in the 200M individual Medley in a time of 2:03.27.',
      'Eric Lee places 58th in the 200M backstroke in a time of 2:04.08.',
      'Congratulations to all of our Olympic Trials qualifiers!',
    ],
  },
  'olympic-trials-goodluck': {
    tag: 'Competition',
    date: 'June 12, 2024',
    title: 'Good Luck to Our Olympic Trials Qualifers!',
    img: '/peakaquatics1/photos/kate-diving.jpg',
    imgPos: 'center 40%',
    excerpt: 'Congratulations to Kate Hurst, Chloe Kim, Richard Poplawski and Eric Lee! Go USA!',
    body: [
      'June 15 - 23, 2024 - Lucas Oil Stadium, IN',
      'Congratulations to Kate Hurst, Chloe Kim, Richard Poplawski and Eric Lee! Go USA!',
    ],
  },
  'kayla-northwestern': {
    tag: 'College Commitment',
    date: 'April 26, 2024',
    title: 'Kayla Rodriguez Commits to Northwestern University',
    img: 'https://images.squarespace-cdn.com/content/v1/613a5c22540e534e72bda9a1/baf4b40c-a32d-40fd-958a-26a5dca41270/Kayla+Northwestern.jpg',
    imgPos: 'center 20%',
    excerpt: '"I am so blessed to announce my verbal commitment to continue my academic and athletic career at Northwestern University!"',
    body: [
      '"I am so blessed to announce my verbal commitment to continue my academic and athletic career at Northwestern University! I would most importantly like to thank my family, coaches, friends and teammates for supporting me along the way. I would also like to thank the amazing staff at NU for giving me this opportunity. Go \'Cats\uD83D\uDC9C\uD83D\uDE3C"',
      'Congratulations on the commitment Kayla and family!',
    ],
  },
  'chloe-princeton': {
    tag: 'College Commitment',
    date: 'March 3, 2024',
    title: 'Chloe Kim Commits to Princeton University',
    img: 'https://images.squarespace-cdn.com/content/v1/613a5c22540e534e72bda9a1/6873bb94-09ca-42c5-b9fb-4414ceef4fb3/Chloe+Princeteonn.jpg',
    imgPos: 'center 20%',
    excerpt: '"I am so honored to announce my verbal commitment to the admissions process at Princeton University!"',
    body: [
      '"I am so honored to announce my verbal commitment to the admissions process at Princeton University! Thank you to my family, friends, teammates, and coaches for supporting me throughout this process. A special thank you to coach Abby for giving me this incredible opportunity. GO TIGERS!! \uD83D\uDC05\uD83D\uDC05"',
      'Congratulations to Chloe Kim and to her family!',
    ],
  },
  'kate-worlds-9th': {
    tag: 'World Championships',
    date: 'February 12, 2024',
    title: 'Congratulations Kate Hurst',
    img: 'https://images.squarespace-cdn.com/content/v1/613a5c22540e534e72bda9a1/f487e314-a213-4ca9-851f-95a0088c97e4/Kate+USA+2.jpg',
    imgPos: 'center 30%',
    excerpt: 'Kate Hurst places 9th in the world in the 1500m Freestyle at the 2024 World Aquatics Championships!',
    body: [
      '2024 World Aquatics Championships',
      '02-18 Sept 2023 - Doha, Qatar',
      'Kate Hurst places 9th in the world in the 1500m Freestyle with the time of 16:18.83. Congratulations and welcome back!',
    ],
  },
  'kate-worlds-represent': {
    tag: 'World Championships',
    date: 'February 5, 2024',
    title: 'Kate Hurst Represents Team USA At World Aquatics Championships',
    img: 'https://images.squarespace-cdn.com/content/v1/613a5c22540e534e72bda9a1/8dc06c07-21e9-4109-8efb-80173e43edf3/Kate+Hurst+%26+Ken+O%27Reilly.jpg',
    imgPos: 'center 30%',
    excerpt: 'Congratulations to USA National Team Member Kate Hurst for representing the red, white and blue at the world stage!',
    body: [
      '2024 World Aquatics Championships',
      '02-18 Sept 2023 - Doha, Qatar',
      'Congratulations to USA National Team Member Kate Hurst for representing the red, white and blue at the world stage alongside coach Kenneth O\'Reilly from Scarlet Aquatics!',
      'GO USA!',
    ],
  },
  'kate-wins-gold': {
    tag: 'World Championships',
    date: 'September 10, 2023',
    title: 'Kate Hurst Wins Gold for Team USA',
    img: 'https://images.squarespace-cdn.com/content/v1/613a5c22540e534e72bda9a1/1b92052f-fb66-46b7-940d-fcc862a1e60f/Kate+Wins.jpg',
    imgPos: 'center 30%',
    excerpt: 'Kate Hurst becomes a World Junior National Champion in the 1500M Freestyle with a time of 16:09.37!',
    body: [
      '2023 World Aquatics Junior Swimming Championships',
      '04-09 Sept 2023 - Wingate Institute - Israel, Netanya',
      'The World Aquatics Junior Swimming Championships is the highest level competition for swimmers globally under the age of 18. Kate Hurst of Scarlet Aquatic\'s became a World Junior National Champion this past weekend in the 1500M Freestyle with a time of 16:09.37.',
      'The time ranks her 12th all time in United States history and places her fourth in the country. She dropped nearly 10 seconds from her previous best time at the 2023 Summer Junior National Championships earlier this month. Kate has become part of the USA National Team after her performance.',
      'Congratulations to Kate & her family!',
    ],
  },
  'speedo-juniors-2023': {
    tag: 'Competition',
    date: 'August 5, 2023',
    title: '2023 Speedo Junior National Championships',
    img: 'https://images.squarespace-cdn.com/content/v1/613a5c22540e534e72bda9a1/452e648c-5a8b-4cbb-99ad-57459dde132d/Timothy+Lee.jpg',
    imgPos: 'center 30%',
    excerpt: 'Kate Hurst finishes 2nd in the 1500M Freestyle dropping nearly 10 seconds. Timothy Lee makes his first Summer Junior National Cut!',
    body: [
      '07/31/23 - 08/04/23 - William Woollett Jr. Aquatic Center Irvine, CA',
      '7/29: On day 1 of the 2023 Summer Junior National Championships, Kate Hurst of Scarlet Aquatic\'s posts a lifetime best of 8:34.11, placing third in the 800M Freestyle. Kate dropped nearly 9 seconds from her pervious best. Chloe Kim finishes 12th in a time of 8:49.86.',
      'Kayla Rodriguez also makes her first appearance and swims best times in the 100M Breaststroke and 200M Breaststroke in a time of 1:13.29 & 2:38.92 respectively.',
      '8/1: Grace Lee makes her debut on this stage making her first Summer Junior National cut in the 800M Freestyle in a time of 8:54.29, dropping nearly 17 seconds.',
      '8/2: Kate Hurst swims a lifetime best of 4:11.71 and places third overall dropping over 2 seconds from her previous time of 4:14.27.',
      '8/4: In the Women\'s 1500M Freestyle, Kate Hurst finishes 2nd in the 1500M Freestyle in a lifetime best time of 16:18.55 dropping nearly 10 seconds. Timothy Lee also makes his first Summer Junior National Cut in his 50M freestyle in a time of 23.98.',
    ],
  },
  'grace-cornell': {
    tag: 'College Commitment',
    date: 'July 27, 2023',
    title: 'Grace Lee Commits to Cornell University',
    img: 'https://images.squarespace-cdn.com/content/v1/613a5c22540e534e72bda9a1/075a4869-24f3-4e07-8988-7175b5270e9d/Grace+Lee+Testimonial.jpg',
    imgPos: 'center 20%',
    excerpt: '"I\'m thrilled to announce my verbal commitment to further my academic and swim career at Cornell University!"',
    body: [
      '"I\'m thrilled to announce my verbal commitment to further my academic and swim career at Cornell University! Thank you Coach Pat and Coach Eileen for giving me this opportunity. I would also like to thank my coaches, teammates, friends, and family for supporting me through this process. GO BIG RED \uD83D\uDC3B\u2764\uFE0F"',
      'Congratulations to Grace Lee and to her family!',
    ],
  },
  'doyee-westpoint': {
    tag: 'College Commitment',
    date: 'July 9, 2023',
    title: 'Doyee Kim Commits to West Point',
    img: 'https://images.squarespace-cdn.com/content/v1/613a5c22540e534e72bda9a1/ed52330b-b6a9-4d30-b985-6a48bf62cf69/Doyee+Kim.jpg',
    imgPos: 'center 20%',
    excerpt: '"I am so blessed to announce my commitment to United States Military Academy."',
    body: [
      '"I am so blessed to announce my commitment to United States Military Academy. I\'d like to thank God, my family, coaches, and teammates for guiding me along this journey. #AGTG #GoARMY"',
      'Congratulations to Doyee and his family!',
    ],
  },
  'richard-harvard': {
    tag: 'College Commitment',
    date: 'November 3, 2022',
    title: 'Richard Poplawski Commits to Harvard University',
    img: 'https://images.squarespace-cdn.com/content/v1/613a5c22540e534e72bda9a1/ab3694de-efbc-4bf4-9ec2-41c8fc789802/Richard-Poplawski-By-Jack-Spitser-AL2I9007-1-scaled.jpg',
    imgPos: 'center 20%',
    excerpt: '"I am honored and excited to announce my verbal commitment to the admissions process to continue my academic and athletic career at Harvard University."',
    body: [
      '"I am honored and excited to announce my verbal commitment to the admissions process to continue my academic and athletic career at Harvard University. I would like to thank my family, coaches, and friends who have continuously supported me throughout the years. And a huge thanks to Coach Kevin and Coach Daniel for giving me this awesome opportunity. Go Crimson!"',
      'Congratulations to Richard and family! Best of luck with Eric!',
    ],
  },
  'eric-harvard': {
    tag: 'College Commitment',
    date: 'November 3, 2022',
    title: 'Eric Lee Commits to Harvard University',
    img: 'https://images.squarespace-cdn.com/content/v1/613a5c22540e534e72bda9a1/a15eaafa-79cb-426c-9b27-3325a0a28fed/Eric+Lee+Testimonial.jpg',
    imgPos: 'center 20%',
    excerpt: 'Congratulations Eric Lee! Job well done!',
    body: [
      'Congratulations Eric Lee! Job well done!',
    ],
  },
  'chloe-wins-400im': {
    tag: 'Competition',
    date: 'August 6, 2022',
    title: 'Chloe Kim Wins the 400 Individual Medley at the Speedo Junior National Championships',
    img: 'https://images.squarespace-cdn.com/content/v1/613a5c22540e534e72bda9a1/3d0b4d58-3215-4640-95dc-ea08e4f7ed70/Chloe-Kim-By-Jack-Spitser-CD8I1009-1080x720.jpg',
    imgPos: 'center 30%',
    excerpt: 'Chloe Kim becomes a Junior National Champion in the 400 Individual Medley in a time of 4:43.45!',
    body: [
      '2022 Speedo Junior National Championships',
      '08/01/22 - 08/05/22 - William Woollett Jr. Aquatic Center Irvine, CA',
      'Chloe Kim of Scarlet Aquatic\'s becomes a Junior National Champion in the 400 Individual Medley in a time of 4:43.45. The time ranks her 28th all time in the 15-16 National Age Group rankings.',
      'Chloe Kim also took 2nd place in the 1500M Freestyle with a time of 16:28.77, which ranks her 38th all time in the 15-16 age group. Kate Hurst took 3rd in a lifetime best of 16:37.22 which ranks her 75th all time in the 15-16 age group.',
      'Chloe and Kate placed 4th & 5th respectively in the 800M Freestyle in a time of 8:44.88 and 8:45.83. Both personal best times for the duo.',
      'Kate clocked in a 4:15.49 during prelims in her 400M Freestyle placing 8th at finals alongside Chloe with a best time of 4:16.59.',
      'Eric Lee places 8th in the 400M Individual Medley going a best time of 4:26.05, which is just shy of the Olympic Trial Cut of 4:25.19. He also goes a best time of 2:05.15 in the 200M Individual Medley and 2:04.40 in the 200M backstroke placing 12th and 21st respectively.',
      'Richard Poplawski goes a best time of 2:02.36 in the 200M butterfly and places 22nd overall.',
    ],
  },
}

export const NEWS_LIST = [
  { id: 'ethan-state-record', featured: true },
  { id: 'tyr-2026' },
  { id: 'chloe-worlds' },
  { id: 'jonas-wesleyan' },
  { id: 'rebekah-rochester' },
  { id: 'jacob-cmu' },
  { id: 'jessica-colgate' },
  { id: 'sienna-holycross' },
  { id: 'harrison-lehigh' },
  { id: 'junior-nationals-qualifiers' },
  { id: 'chloe-qualifies-worlds' },
  { id: 'ymca-nationals-2025' },
  { id: 'east-coast-elite-2025' },
  { id: 'speedo-sectionals-2025' },
  { id: 'njs-scarlet-gold-2025' },
  { id: 'holiday-classic-2025' },
  { id: 'winter-juniors-2024' },
  { id: 'roy-lafayette' },
  { id: 'timothy-harvard' },
  { id: 'kate-national' },
  { id: 'speedo-summer-2024' },
  { id: 'olympic-trials' },
  { id: 'olympic-trials-goodluck' },
  { id: 'kayla-northwestern' },
  { id: 'chloe-princeton' },
  { id: 'kate-worlds-9th' },
  { id: 'kate-worlds-represent' },
  { id: 'kate-wins-gold' },
  { id: 'speedo-juniors-2023' },
  { id: 'grace-cornell' },
  { id: 'doyee-westpoint' },
  { id: 'richard-harvard' },
  { id: 'eric-harvard' },
  { id: 'chloe-wins-400im' },
]

export const RECORDS_HERO = [
  { time: '1:45.33', event: '200 Yard Backstroke',          swimmer: 'Eric Lee',          badge: 'Boys All-Time SCY',  photo: '/peakaquatics1/athletes/eric-lee.webp' },
  { time: '4:07.11', event: '400 Yard Individual Medley',   swimmer: 'Chloe Kim',         badge: 'Girls All-Time SCY', photo: '/peakaquatics1/athletes/chloe-kim.webp' },
  { time: '2:03.26', event: '200 Meter Individual Medley',  swimmer: 'Richard Poplawski', badge: 'Boys All-Time LCM · Harvard University · Top 50 at Olympic Trials',  photo: '/peakaquatics1/athletes/richard-poplawski.webp' },
  { time: '16:09.37',event: '1500 Meter Freestyle',         swimmer: 'Kate Hurst',        badge: 'Girls All-Time LCM · 12th in US History', photo: 'https://dxbhsrqyrr690.cloudfront.net/sidearm.nextgen.sites/texassports_com/images/2024/9/4/__0014_Hurst_Kate-2024.jpg' },
]

// ─────────────────────────────────────────────────────────────
// RECORDS DATA — Easy to edit!
//
// To add/update a record, find the category and event, then change:
//   { name: 'Swimmer Name', time: '1:23.45', year: 2025 }
//
// Each event has: first, second, third (3 place finishers)
// ─────────────────────────────────────────────────────────────

function r(event, first, second, third) {
  return { event, first, second, third }
}
function p(name, time, year) {
  return { name, time, year }
}

// Convert new format to the array format the components expect
function buildTable(label, records) {
  return {
    label,
    threeCol: true,
    rows: records.map(r => [
      r.event,
      r.first.name,  r.first.time,  String(r.first.year),
      r.second.name, r.second.time, String(r.second.year),
      r.third.name,  r.third.time,  String(r.third.year),
    ]),
  }
}

export const RECORDS_TABLES = {

  // ═══════════════════════════════════════════════════════════
  // SCY BOYS 14 & UNDER
  // ═══════════════════════════════════════════════════════════
  'scy-boys-14': buildTable('SCY Boys 14 & Under', [
    r('50 Free',    p('Ryker Levi',          '21.18',    2025), p('Timothy Lee',         '21.32',    2022), p('Richard Poplawski',  '21.98',    2021)),
    r('100 Free',   p('Ryker Levi',          '45.89',    2025), p('Timothy Lee',         '46.29',    2022), p('Ethan Reines',       '48.15',    2026)),
    r('200 Free',   p('Richard Poplawski',   '1:41.85',  2021), p('Chase Kim',           '1:43.56',  2026), p('Timothy Lee',        '1:43.82',  2022)),
    r('500 Free',   p('Ethan Reines',        '4:30.88',  2026), p('Richard Poplawski',   '4:32.81',  2021), p('Timothy Lee',        '4:34.86',  2022)),
    r('1000 Free',  p('Timothy Lee',         '9:23.58',  2022), p('Ethan Reines',        '9:28.33',  2026), p('Woori Lee',          '9:46.02',  2022)),
    r('1650 Free',  p('Timothy Lee',         '15:47.71', 2022), p('Ethan Reines',        '15:48.39', 2026), p('Eric Lee',           '15:58.00', 2020)),
    r('100 Back',   p('Ryker Levi',          '50.84',    2025), p('Eric Lee',            '51.84',    2020), p('Matthew Jun',        '52.01',    2024)),
    r('200 Back',   p('Richard Poplawski',   '1:47.78',  2021), p('Eric Lee',            '1:52.28',  2020), p('Yuriel Lee',         '1:53.39',  2024)),
    r('100 Fly',    p('Ryker Levi',          '49.64',    2025), p('Richard Poplawski',   '50.43',    2020), p('Timothy Lee',        '50.63',    2022)),
    r('200 Fly',    p('Richard Poplawski',   '1:48.61',  2021), p('Chase Kim',           '1:50.88',  2026), p('Timothy Lee',        '1:52.68',  2022)),
    r('100 Breast', p('Ethan Reines',        '59.11',    2026), p('Connor Hong',         '59.18',    2023), p('Woori Lee',          '1:00.07',  2022)),
    r('200 Breast', p('Eric Lee',            '2:07.42',  2020), p('Connor Hong',         '2:07.77',  2023), p('Ethan Reines',       '2:08.52',  2026)),
    r('200 IM',     p('Richard Poplawski',   '1:50.50',  2021), p('Timothy Lee',         '1:53.89',  2022), p('Connor Hong',        '1:55.51',  2023)),
    r('400 IM',     p('Richard Poplawski',   '3:57.14',  2021), p('Ethan Reines',        '3:59.61',  2026), p('Connor Hong',        '4:05.66',  2023)),
  ]),

  // ═══════════════════════════════════════════════════════════
  // SCY GIRLS 14 & UNDER
  // ═══════════════════════════════════════════════════════════
  'scy-girls-14': buildTable('SCY Girls 14 & Under', [
    r('50 Free',    p('Elizabeth Mulder',  '24.01',    2025), p('Emma Zhang',          '24.57',    2026), p('Labdron Namgyal',    '24.65',    2025)),
    r('100 Free',   p('Chloe Kim',        '51.63',    2022), p('Susie Lee',           '54.31',    2019), p('Rebekah Jung',       '55.67',    2022)),
    r('200 Free',   p('Chloe Kim',        '1:49.33',  2022), p('Ava Lan',             '1:54.69',  2025), p('Susie Lee',          '1:55.16',  2019)),
    r('500 Free',   p('Chloe Kim',        '4:46.80',  2022), p('Ava Lan',             '4:56.56',  2026), p('Susie Lee',          '4:56.80',  2020)),
    r('1000 Free',  p('Chloe Kim',        '9:50.57',  2022), p('Ava Lan',             '10:09.18', 2025), p('Kate Hurst',         '10:12.92', 2020)),
    r('1650 Free',  p('Chloe Kim',        '16:16.21', 2022), p('Kate Hurst',          '17:01.89', 2020), p('Lauren Muller',      '17:29.81', 2021)),
    r('100 Back',   p('Chloe Kim',        '56.90',    2022), p('Susie Lee',           '56.90',    2020), p('Rebekah Jung',       '58.89',    2022)),
    r('200 Back',   p('Chloe Kim',        '1:59.98',  2022), p('Susie Lee',           '2:03.96',  2019), p('Rebekah Jung',       '2:06.91',  2022)),
    r('100 Fly',    p('Chloe Kim',        '56.94',    2022), p('Jessica Sung',        '57.50',    2025), p('Emma Zhang',         '57.75',    2026)),
    r('200 Fly',    p('Chloe Kim',        '2:02.81',  2022), p('Susie Lee',           '2:05.83',  2019), p('Jessica Sung',       '2:09.26',  2025)),
    r('100 Breast', p('Stephanie Kim',    '1:04.06',  2024), p('Emma Zhang',          '1:04.81',  2026), p('Madelyn Raguindin',  '1:06.64',  2023)),
    r('200 Breast', p('Chloe Kim',        '2:16.12',  2022), p('Madelyn Raguindin',   '2:20.37',  2023), p('Stephanie Kim',      '2:21.68',  2024)),
    r('200 IM',     p('Chloe Kim',        '2:00.01',  2022), p('Emma Zhang',          '2:06.84',  2026), p('Susie Lee',          '2:07.32',  2020)),
    r('400 IM',     p('Chloe Kim',        '4:13.13',  2022), p('Ava Lan',             '4:27.39',  2025), p('Susie Lee',          '4:28.05',  2019)),
  ]),

  // ═══════════════════════════════════════════════════════════
  // LCM BOYS 14 & UNDER
  // ═══════════════════════════════════════════════════════════
  'lcm-boys-14': buildTable('LCM Boys 14 & Under', [
    r('50 Free',    p('Timothy Lee',         '24.44',    2022), p('Ryker Levi',          '24.66',    2025), p('Matthew Jun',        '25.71',    2024)),
    r('100 Free',   p('Timothy Lee',         '53.01',    2022), p('Ryker Levi',          '54.60',    2025), p('Matthew Jun',        '55.21',    2024)),
    r('200 Free',   p('Ethan Reines',        '1:58.18',  2026), p('Timothy Lee',         '1:58.73',  2022), p('Richard Poplawski',  '1:58.82',  2020)),
    r('400 Free',   p('Timothy Lee',         '4:06.98',  2022), p('Ethan Reines',        '4:08.91',  2026), p('Richard Poplawski',  '4:12.84',  2021)),
    r('800 Free',   p('Ethan Reines',        '8:35.01',  2025), p('Timothy Lee',         '8:39.61',  2022), p('Justin Yoo',         '9:01.26',  2024)),
    r('1500 Free',  p('Ethan Reines',        '16:12.64', 2026), p('Timothy Lee',         '16:42.38', 2022), p('Caden Cho',          '17:05.50', 2024)),
    r('100 Back',   p('Richard Poplawski',   '1:00.83',  2020), p('Yuriel Lee',          '1:00.86',  2024), p('Woori Lee',          '1:01.62',  2022)),
    r('200 Back',   p('Richard Poplawski',   '2:06.12',  2021), p('Ethan Reines',        '2:10.03',  2026), p('Yuriel Lee',         '2:11.46',  2024)),
    r('100 Fly',    p('Richard Poplawski',   '57.07',    2021), p('Ryker Levi',          '57.88',    2025), p('Timothy Lee',        '58.24',    2025)),
    r('200 Fly',    p('Richard Poplawski',   '2:05.53',  2021), p('Chase Kim',           '2:07.83',  2026), p('Ryker Levi',         '2:08.65',  2025)),
    r('100 Breast', p('Connor Hong',         '1:09.27',  2023), p('Eric Lee',            '1:09.77',  2020), p('Woori Lee',          '1:10.47',  2022)),
    r('200 Breast', p('Connor Hong',          '2:29.62',  2023), p('Joshua Reines',       '2:29.94',  2023), p('Richard Poplawski',  '2:31.25',  2021)),
    r('200 IM',     p('Richard Poplawski',   '2:06.42',  2021), p('Woori Lee',           '2:12.96',  2022), p('Ethan Reines',       '2:14.52',  2025)),
    r('400 IM',     p('Richard Poplawski',   '4:30.31',  2021), p('Ethan Reines',        '4:37.63',  2026), p('Eric Lee',           '4:43.53',  2020)),
  ]),

  // ═══════════════════════════════════════════════════════════
  // LCM GIRLS 14 & UNDER
  // ═══════════════════════════════════════════════════════════
  'lcm-girls-14': buildTable('LCM Girls 14 & Under', [
    r('50 Free',    p('Chloe Kim',      '27.72',    2022), p('Emma Zhang',        '28.44',    2025), p('Jessica Sung',       '28.52',    2025)),
    r('100 Free',   p('Chloe Kim',      '59.36',    2022), p('Emma Zhang',        '1:01.73',  2025), p('Rebekah Jung',       '1:01.87',  2022)),
    r('200 Free',   p('Chloe Kim',      '2:04.81',  2022), p('Ava Lan',           '2:09.09',  2026), p('Emma Zhang',         '2:11.40',  2025)),
    r('400 Free',   p('Chloe Kim',      '4:18.60',  2022), p('Ava Lan',           '4:26.15',  2026), p('Susie Lee',          '4:30.82',  2019)),
    r('800 Free',   p('Chloe Kim',      '8:47.86',  2022), p('Ava Lan',           '9:09.68',  2026), p('Susie Lee',          '9:17.66',  2020)),
    r('1500 Free',  p('Chloe Kim',      '16:36.10', 2022), p('Ava Lan',           '17:27.68', 2026), p('Lauren Muller',      '18:23.22', 2022)),
    r('100 Back',   p('Chloe Kim',      '1:05.04',  2022), p('Susie Lee',         '1:07.27',  2019), p('Rebekah Jung',       '1:07.63',  2022)),
    r('200 Back',   p('Chloe Kim',      '2:17.48',  2022), p('Susie Lee',         '2:24.65',  2019), p('Rebekah Jung',       '2:24.69',  2022)),
    r('100 Fly',    p('Chloe Kim',      '1:03.79',  2022), p('Jessica Sung',      '1:04.92',  2025), p('Susie Lee',          '1:05.93',  2019)),
    r('200 Fly',    p('Chloe Kim',      '2:19.50',  2022), p('Jessica Sung',      '2:22.80',  2025), p('Susie Lee',          '2:24.06',  2019)),
    r('100 Breast', p('Stephanie Kim',  '1:13.91',  2024), p('Emma Zhang',        '1:13.98',  2025), p('Chloe Kim',          '1:14.87',  2022)),
    r('200 Breast', p('Chloe Kim',      '2:38.66',  2022), p('Stephanie Kim',     '2:38.75',  2024), p('Madelyn Raguindin',  '2:44.55',  2023)),
    r('200 IM',     p('Chloe Kim',      '2:18.79',  2022), p('Ava Lan',           '2:25.31',  2026), p('Susie Lee',          '2:25.46',  2019)),
    r('400 IM',     p('Chloe Kim',      '4:51.63',  2022), p('Susie Lee',         '5:04.43',  2019), p('Ava Lan',            '5:06.04',  2026)),
  ]),

  // ═══════════════════════════════════════════════════════════
  // SCY MEN'S OPEN
  // ═══════════════════════════════════════════════════════════
  'scy-men': buildTable("SCY Men's Open", [
    r('50 Free',    p('Timothy Lee',         '20.54',    2024), p('Ryker Levi',          '20.56',    2025), p('Richard Poplawski',    '20.81',    2023)),
    r('100 Free',   p('Timothy Lee',         '44.71',    2024), p('Richard Poplawski',   '45.18',    2023), p('Eric Lee',             '46.23',    2023)),
    r('200 Free',   p('Richard Poplawski',   '1:37.90',  2023), p('Timothy Lee',         '1:38.75',  2025), p('Ryker Levi',           '1:39.61',  2025)),
    r('500 Free',   p('Richard Poplawski',   '4:28.84',  2023), p('Steven Bendoraitis',  '4:29.22',  2022), p('Christopher Chang',    '4:29.52',  2022)),
    r('1000 Free',  p('Steven Bendoraitis',  '9:08.65',  2022), p('Eric Lee',            '9:18.38',  2022), p('Raymond Stelmark',     '9:20.12',  2023)),
    r('1650 Free',  p('Steven Bendoraitis',  '15:17.44', 2022), p('Christopher Chang',   '15:40.96', 2022), p('Richard Poplawski',    '15:42.14', 2023)),
    r('100 Back',   p('Eric Lee',            '48.69',    2023), p('Jacob Kim',           '49.57',    2025), p('Richard Poplawski',    '49.61',    2022)),
    r('200 Back',   p('Eric Lee',            '1:45.33',  2023), p('Richard Poplawski',   '1:47.02',  2022), p('Yuriel Lee',           '1:49.58',  2025)),
    r('100 Fly',    p('Ryker Levi',          '46.94',    2026), p('Richard Poplawski',   '48.16',    2024), p('Harrison Lee',         '48.96',    2025)),
    r('200 Fly',    p('Richard Poplawski',   '1:46.59',  2023), p('Eric Lee',            '1:47.49',  2022), p('Ryker Levi',           '1:47.52',  2026)),
    r('100 Breast', p('Dimitri Melnikov',    '54.75',    2025), p('Doyee Kim',           '54.91',    2024), p('Eric Lee',             '55.04',    2024)),
    r('200 Breast', p('Dimitri Melnikov',    '2:00.26',  2025), p('Eric Lee',            '2:00.62',  2022), p('Doyee Kim',            '2:00.80',  2023)),
    r('200 IM',     p('Eric Lee',            '1:46.66',  2023), p('Richard Poplawski',   '1:47.87',  2022), p('Timothy Lee',          '1:49.61',  2025)),
    r('400 IM',     p('Eric Lee',            '3:49.01',  2023), p('Richard Poplawski',   '3:49.55',  2023), p('Timothy Lee',          '3:58.37',  2024)),
  ]),

  // ═══════════════════════════════════════════════════════════
  // SCY WOMEN'S OPEN
  // ═══════════════════════════════════════════════════════════
  'scy-women': buildTable("SCY Women's Open", [
    r('50 Free',    p('Chloe Kim',         '23.28',    2025), p('Elizabeth Mulder',  '23.71',    2025), p('Jessica Wolf',       '23.90',    2025)),
    r('100 Free',   p('Jessica Wolf',      '50.64',    2025), p('Chloe Kim',         '51.42',    2023), p('Grace Lee',          '51.67',    2022)),
    r('200 Free',   p('Chloe Kim',         '1:47.52',  2024), p('Kate Hurst',        '1:47.95',  2023), p('Grace Lee',          '1:51.14',  2023)),
    r('500 Free',   p('Chloe Kim',         '4:42.33',  2024), p('Kate Hurst',        '4:43.46',  2023), p('Grace Lee',          '4:56.20',  2023)),
    r('1000 Free',  p('Kate Hurst',        '9:34.03',  2023), p('Chloe Kim',         '9:42.69',  2022), p('Ava Lan',            '10:08.61', 2026)),
    r('1650 Free',  p('Chloe Kim',         '16:00.21', 2024), p('Kate Hurst',        '16:08.25', 2023), p('Grace Lee',          '16:59.79', 2023)),
    r('100 Back',   p('Chloe Kim',         '54.37',    2025), p('Rebekah Jung',      '56.99',    2025), p('Grace Lee',          '58.95',    2023)),
    r('200 Back',   p('Chloe Kim',         '1:55.33',  2024), p('Rebekah Jung',      '2:02.07',  2025), p('Sienna Cho',         '2:03.04',  2026)),
    r('100 Fly',    p('Chloe Kim',         '53.48',    2024), p('Jessica Sung',      '56.19',    2025), p('Kayla Rodriguez',    '56.93',    2023)),
    r('200 Fly',    p('Chloe Kim',         '1:56.19',  2025), p('Kate Hurst',        '2:00.77',  2024), p('Jessica Sung',       '2:04.17',  2025)),
    r('100 Breast', p('Kayla Rodriguez',   '1:02.38',  2023), p('Stephanie Kim',     '1:03.38',  2025), p('Chloe Kim',          '1:03.51',  2025)),
    r('200 Breast', p('Kayla Rodriguez',   '2:14.33',  2023), p('Stephanie Kim',     '2:15.43',  2025), p('Chloe Kim',          '2:16.12',  2022)),
    r('200 IM',     p('Chloe Kim',         '1:59.30',  2024), p('Kate Hurst',        '2:03.24',  2023), p('Rebekah Jung',       '2:06.04',  2024)),
    r('400 IM',     p('Chloe Kim',         '4:07.11',  2024), p('Kate Hurst',        '4:14.82',  2023), p('Stephanie Kim',      '4:26.61',  2025)),
  ]),

  // ═══════════════════════════════════════════════════════════
  // LCM MEN'S OPEN
  // ═══════════════════════════════════════════════════════════
  'lcm-men': buildTable("LCM Men's Open", [
    r('50 Free',    p('Richard Poplawski',   '23.53',    2024), p('Timothy Lee',         '23.82',    2024), p('Ryker Levi',           '23.89',    2026)),
    r('100 Free',   p('Timothy Lee',         '51.75',    2024), p('Richard Poplawski',   '51.81',    2024), p('Michael Granin',       '52.46',    2024)),
    r('200 Free',   p('Richard Poplawski',   '1:51.74',  2024), p('Jacob Kim',           '1:55.07',  2024), p('Timothy Lee',          '1:55.28',  2025)),
    r('400 Free',   p('Steven Bendoraitis',  '4:01.27',  2022), p('Richard Poplawski',   '4:01.30',  2024), p('Raymond Stelmark',     '4:02.33',  2024)),
    r('800 Free',   p('Steven Bendoraitis',  '8:15.39',  2022), p('Christopher Chang',   '8:20.10',  2022), p('Richard Poplawski',    '8:26.94',  2023)),
    r('1500 Free',  p('Steven Bendoraitis',  '15:40.72', 2022), p('Christopher Chang',   '16:02.03', 2022), p('Raymond Stelmark',     '16:11.10', 2024)),
    r('100 Back',   p('Eric Lee',            '56.89',    2023), p('Jacob Kim',           '57.82',    2025), p('Richard Poplawski',    '58.39',    2023)),
    r('200 Back',   p('Eric Lee',            '2:01.63',  2023), p('Richard Poplawski',   '2:03.33',  2024), p('Yuriel Lee',           '2:08.21',  2025)),
    r('100 Fly',    p('Ryker Levi',          '54.64',    2026), p('Richard Poplawski',   '54.96',    2024), p('Timothy Lee',          '56.34',    2025)),
    r('200 Fly',    p('Richard Poplawski',   '2:01.40',  2024), p('Ryker Levi',          '2:02.87',  2026), p('Eric Lee',             '2:06.07',  2023)),
    r('100 Breast', p('Eric Lee',            '1:04.49',  2023), p('Dimitri Melnikov',    '1:05.18',  2024), p('Jason Yi',             '1:06.03',  2022)),
    r('200 Breast', p('Joshua Reines',       '2:20.91',  2026), p('Eric Lee',            '2:21.52',  2022), p('Michael Granin',       '2:23.48',  2024)),
    r('200 IM',     p('Richard Poplawski',   '2:03.26',  2024), p('Eric Lee',            '2:04.96',  2022), p('Timothy Lee',          '2:08.05',  2025)),
    r('400 IM',     p('Richard Poplawski',   '4:24.52',  2024), p('Eric Lee',            '4:26.05',  2022), p('Joshua Reines',        '4:33.93',  2026)),
  ]),

  // ═══════════════════════════════════════════════════════════
  // LCM WOMEN'S OPEN
  // ═══════════════════════════════════════════════════════════
  'lcm-women': buildTable("LCM Women's Open", [
    r('50 Free',    p('Jessie Wolf',       '27.07',    2025), p('Chloe Kim',         '27.26',    2025), p('Grace Lee',          '27.53',    2022)),
    r('100 Free',   p('Kate Hurst',        '57.27',    2024), p('Jessie Wolf',       '58.36',    2025), p('Chloe Kim',          '58.44',    2022)),
    r('200 Free',   p('Kate Hurst',        '2:00.32',  2024), p('Chloe Kim',         '2:02.85',  2025), p('Grace Lee',          '2:04.83',  2023)),
    r('400 Free',   p('Kate Hurst',        '4:10.89',  2024), p('Chloe Kim',         '4:15.02',  2025), p('Kathleen Turano',    '4:19.53',  2025)),
    r('800 Free',   p('Kate Hurst',        '8:28.92',  2024), p('Chloe Kim',         '8:42.31',  2025), p('Kathleen Turano',    '8:51.43',  2025)),
    r('1500 Free',  p('Kate Hurst',        '16:09.37', 2023), p('Chloe Kim',         '16:22.56', 2025), p('Kathleen Turano',    '16:59.01', 2025)),
    r('100 Back',   p('Chloe Kim',         '1:04.96',  2023), p('Rebekah Jung',      '1:06.14',  2024), p('Grace Lee',          '1:08.52',  2024)),
    r('200 Back',   p('Chloe Kim',         '2:17.40',  2025), p('Rebekah Jung',      '2:23.67',  2024), p('Kate Hurst',         '2:24.37',  2023)),
    r('100 Fly',    p('Chloe Kim',         '1:01.92',  2025), p('Kate Hurst',        '1:04.43',  2023), p('Kayla Rodriguez',    '1:04.68',  2025)),
    r('200 Fly',    p('Chloe Kim',         '2:12.69',  2025), p('Kate Hurst',        '2:17.46',  2023), p('Kathleen Turano',    '2:19.31',  2025)),
    r('100 Breast', p('Kayla Rodriguez',   '1:12.54',  2025), p('Stephanie Kim',     '1:13.23',  2025), p('Chloe Kim',          '1:14.87',  2022)),
    r('200 Breast', p('Chloe Kim',         '2:35.36',  2022), p('Stephanie Kim',     '2:35.83',  2025), p('Kayla Rodriguez',    '2:35.88',  2025)),
    r('200 IM',     p('Chloe Kim',         '2:16.36',  2025), p('Kate Hurst',        '2:19.35',  2024), p('Grace Lee',          '2:25.89',  2023)),
    r('400 IM',     p('Chloe Kim',         '4:43.32',  2025), p('Kate Hurst',        '4:49.43',  2024), p('Kathleen Turano',    '4:56.38',  2025)),
  ]),
}

const CDN = 'https://images.squarespace-cdn.com/content/v1/613a5c22540e534e72bda9a1/'
export const PLACEMENTS = [
  { name: 'Chloe Kim',            school: 'Princeton University',        photo: '/peakaquatics1/athletes/chloe-kim.webp' },
  { name: 'Eric Lee',             school: 'Harvard University',          photo: '/peakaquatics1/athletes/eric-lee.webp' },
  { name: 'Timothy Lee',          school: 'Harvard University',          year: '2024', photo: CDN + '1730135596929-CT3TH0EQRII0VQI725SB/Timothy+Harvard.jpg' },
  { name: 'Michael Granin',       school: 'Colgate University',          photo: '/peakaquatics1/athletes/michael-granin.webp' },
  { name: 'Jessica Wolf',         school: 'Colgate University',          year: '2025', photo: CDN + '1762189818941-1RC3X9NYU3MKFS7ZVMO6/Jessie+Wolf+commits+to+Colgate+University.jpg' },
  { name: 'Christopher Chang',    school: 'Brown University',            photo: '/peakaquatics1/athletes/chris-chang.webp' },
  { name: 'Grace Lee',            school: 'Cornell University',          photo: '/peakaquatics1/athletes/grace-lee.webp' },
  { name: 'Jacob Kim',            school: 'Carnegie Mellon University',  year: '2025', photo: CDN + '1762190250415-C90XUZ0KXTC5KVENSJJR/Jacob+Commits+to+Carnegie+Mellon.jpg' },
  { name: 'Kayla Rodriguez',      school: 'Northwestern University',     photo: 'https://dxbhsrqyrr690.cloudfront.net/sidearm.nextgen.sites/nusports.com/images/2025/10/7/Rodriguez_Kayla.jpg' },
  { name: 'Steven Bendoraitis',   school: 'TCNJ',           photo: '/peakaquatics1/athletes/steven-bendoraitis.webp' },
  { name: 'Matt Bendoraitis',     school: 'University of Maine',         photo: '/peakaquatics1/athletes/matt-bendoraitis.webp' },
  { name: 'Kathleen Bendoraitis', school: 'University of Maine',         photo: '/peakaquatics1/athletes/kathleen-bendoraitis.webp' },
  { name: 'Doyee Kim',            school: 'West Point',                  photo: 'https://dxbhsrqyrr690.cloudfront.net/sidearm.nextgen.sites/goarmywestpoint.com/images/2024/9/4/KIM_DOYEE.jpg' },
  { name: 'Kate Hurst',           school: 'University of Texas',         photo: 'https://dxbhsrqyrr690.cloudfront.net/sidearm.nextgen.sites/texassports_com/images/2024/9/4/__0014_Hurst_Kate-2024.jpg' },
  { name: 'Richard Poplawski',    school: 'Harvard University',          photo: '/peakaquatics1/athletes/richard-poplawski.webp' },
  { name: 'Rebekah Jung',         school: 'University of Rochester',     year: '2025', photo: CDN + '1763303017571-59SHN1ZWRQIT4OREL4FV/Rebekah+Jung.jpg' },
  { name: 'Jonas Emerson',        school: 'Wesleyan University',         year: '2025', photo: CDN + '61339be2-39e3-418c-862f-47cbd238837c/Wesleyan.jpg' },
  { name: 'Roy Dafinoiu',         school: 'Lafayette College',           year: '2024', photo: CDN + '1730218140435-VXX4ILSW54SKK2N09EEM/Roy+LAF.jpg' },
  { name: 'Harrison Lee',         school: 'Lehigh University',           year: '2025', photo: CDN + '1762189435887-LS6BS9O946JF5B24GILK/Harrison+Lee+commits.jpg' },
  { name: 'Sienna Plutzer',       school: 'Holy Cross University',       year: '2025', photo: CDN + '1762189559773-A432QAWJ3081AJNK604W/Sienna+Sacred+Heart.jpg' },
]

export const TESTIMONIALS = [
  {
    quote: "I had the honor of swimming with Coach Phil for a little over two years. He has helped me exceed my expectations as a swimmer and grow as an individual. It's not often that you come across a coach as dedicated and passionate as Coach Phil is. I would not have become the swimmer I am today without him.",
    name: 'Grace Lee',
    school: 'Cornell University',
    image: '/peakaquatics1/athletes/grace-lee.webp',
  },
  {
    quote: "The opportunity to swim for Coach Phil has been a privilege. With coach Phil's expertise in swimming, technical precision, and his dedication, I was able to develop not only as a swimmer but also as a person. Coach Phil has been a mentor for me throughout my swimming career helping me to prepare for competitions physically and even outside the pool mentally.",
    name: 'Eric Lee',
    school: 'Harvard University',
    image: '/peakaquatics1/athletes/eric-lee.webp',
  },
  {
    quote: "Working with Coach Phil over the past five years has been a unique experience. I started as a scrawny eighth grader with poor technique. Coach Phil developed my strokes to allow me to swim at a higher level. His elite coaching style and attention to detail transformed me as an athlete. I am now committed to swim at Colgate University at the division 1 level. Coach Phil's support impacted me tremendously and I hope he can continue to inspire and motivate future swimmers for years to come.",
    name: 'Michael Granin',
    school: 'Colgate University',
    image: '/peakaquatics1/athletes/michael-granin.webp',
  },
  {
    quote: "Coach Phil is the real deal! Since working with him, I have become stronger and quicker both in and out of the water. His program has shaped me into the elite athlete I am today, and has prepared me well for my collegiate athletic career.",
    name: 'Christopher Chang',
    school: 'Brown University',
    image: '/peakaquatics1/athletes/chris-chang.webp',
  },
  {
    quote: "I had the pleasure of swimming for coach Phil for 3 years. Phil is a great mentor, creating a competitive atmosphere for swimmers to learn and excel. He is a great person to talk to about anything and it's been a blessing to swim for him.",
    name: 'Steven Bendoraitis',
    school: 'TCNJ',
    image: '/peakaquatics1/athletes/steven-bendoraitis.webp',
  },
  {
    quote: "Coach Phil has helped me with not only swimming, but with life. He always leaves a positive impact on all of his swimmers. Helping me become a better person in and out of the pool. Phil is the man!",
    name: 'Doyee Kim',
    school: 'West Point',
    image: 'https://dxbhsrqyrr690.cloudfront.net/sidearm.nextgen.sites/goarmywestpoint.com/images/2024/9/4/KIM_DOYEE.jpg',
  },
  {
    quote: "Swimming with coach Phil has truly been an incredible experience and blessing. His passion and knowledge for the sport has helped me improve my technique and confidence in the water, while also preparing me both mentally and physically for peak performance.",
    name: 'Matt Bendoraitis',
    school: 'University of Maine',
    image: '/peakaquatics1/athletes/matt-bendoraitis.webp',
  },
  {
    quote: "Phil is a passionate coach that cares about all his swimmers' progress. I was fortunate enough to train with Phil and learn many different skills and techniques. We have worked together for some time, and he helped me improve as a swimmer and character, in and out of the water.",
    name: 'Kathleen Bendoraitis',
    school: 'University of Maine',
    image: '/peakaquatics1/athletes/kathleen-bendoraitis.webp',
  },
]

export const ABOUT = {
  mission: 'Peak Aquatic Sports is a swimming consultancy that is dedicated in helping parents and student athletes reach their short term and long term swimming goals. Our mission is to instill strong core values of integrity, humility, and discipline through the sport of swimming.',
  homeIntro: 'Started in 2020, Peak Aquatic Sports is a swimming consultancy that is dedicated in guiding athletes and parents on the long journey of competitive club swimming and its collegiate recruitment process.',
  homeBody: 'From World Aquatics Championships qualifiers to entry level swimmers, we assess each athlete individually and tailor the program to fit their specific physiological and psychological needs to maximize their performance in the water.',
  coachBio: [
    'Philip Kang is a technical swimming coach that has experience teaching age group swimmers (7-14 years of age) to senior level swimmers (15 & Over) that have qualified for the World Aquatics Championships and have won Gold at the Speedo Junior National/World Aquatics Junior Swimming Championships. Philip has also assisted and swam for the National/Sectional team under renowned coach, Kenneth O\'Reilly of Scarlet Aquatics.',
    'Philip was a U.S. Open level swimmer and has swam in Division I & Division III colleges at the Pennsylvania State University and New York University. He placed 8th at the Division III NCAA championships in 2016 in the 400IM.',
    'Philip received his Economics degree from New York University in 2017 and is now proudly partnered with 24 Hour Fitness to coach swimmers full time.',
  ],
  partners: [
    { name: '24 Hour Fitness', img: 'https://images.squarespace-cdn.com/content/v1/613a5c22540e534e72bda9a1/1688644570921-S3QLQDAB9RAB14NLJSLF/1.jpg' },
    { name: 'Scarlet Aquatics', img: 'https://images.squarespace-cdn.com/content/v1/613a5c22540e534e72bda9a1/1688644649296-XZLPDDD2JYEZHZPYE1IA/2.jpg' },
    { name: 'StretchLab', img: 'https://images.squarespace-cdn.com/content/v1/613a5c22540e534e72bda9a1/1697139043272-PO6DG8YL9XKT01W563U8/Stretchlab.jpg' },
  ],
}

export const SERVICES_DATA = [
  {
    icon: 'private',
    title: 'Private Sessions',
    desc: 'Swimmers who decide to take one-on-one lessons will receive the coach\'s full attention for the entirety of the lesson.',
    duration: '1 hour',
  },
  {
    icon: 'semi',
    title: 'Semi-Group Sessions',
    desc: 'Semi group sessions combine the individual attention, specificity of training and stroke refinement of private lessons with the peer interaction of a smaller group lesson.',
    duration: '1.5 hours',
  },
  {
    icon: 'group',
    title: 'Group Sessions',
    desc: 'Group sessions offer social interactions, peer encouragement and motivation with fellow teammates.',
    duration: '1.5 hours',
  },
]

export const FAQS = [
  { q: 'How long are private lessons?',                  a: '1 hour.' },
  { q: 'How long are semi-group and group lessons?',     a: '1.5 hours.' },
  { q: 'Do you train master swimmers and triathletes?',  a: 'Yes — programs are available for masters swimmers and triathletes of all levels.' },
  { q: 'Do you have adult programs?',                    a: 'Yes — adult programs are customized to each individual\'s needs and goals.' },
  { q: 'Do you offer collegiate recruiting guidance?',   a: 'Yes — contact Philip directly for details on collegiate recruiting consulting.' },
  { q: 'What skill levels do you work with?',           a: "Peak Aquatic Sports offers a variety of sessions that will fit the athlete's needs — from entry-level swimmers through nationally ranked juniors." },
]

export const CONTACT_INFO = {
  location: '24 Hour Fitness Ramsey\n150 Triangle Plaza\nRamsey, NJ 07446',
  email: 'Philip.jkang@gmail.com',
  instagram: '@philkangg',
  hours: [
    { season: 'Regular Season', weekday: 'Mon – Fri: 3:30 pm – 9:30 pm', weekend: 'Sat – Sun: 12:00 pm – 6:00 pm' },
    { season: 'Summer Hours',   weekday: 'Mon – Fri: 12:00 pm – 6:00 pm', weekend: 'Sat – Sun: 12:00 pm – 6:00 pm' },
  ],
}
